// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Preferir variáveis de ambiente com fallback para valores atuais
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "https://dmmzwowdbdgszzacrrfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtbXp3b3dkYmRnc3p6YWNycmZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NDUyMTksImV4cCI6MjA3MTEyMTIxOX0.zhTmdTT9viXT9DxYExKv24giEgberbO7GX8cqZUVo1Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});